/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResponderRouteImport } from './routes/responder'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExerciciosRouteImport } from './routes/exercicios'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResponderApostilaIdRouteImport } from './routes/responder.$apostilaId'
import { Route as ApostilaIdRouteImport } from './routes/apostila.$id'

const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponderRoute = ResponderRouteImport.update({
  id: '/responder',
  path: '/responder',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciciosRoute = ExerciciosRouteImport.update({
  id: '/exercicios',
  path: '/exercicios',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponderApostilaIdRoute = ResponderApostilaIdRouteImport.update({
  id: '/$apostilaId',
  path: '/$apostilaId',
  getParentRoute: () => ResponderRoute,
} as any)
const ApostilaIdRoute = ApostilaIdRouteImport.update({
  id: '/apostila/$id',
  path: '/apostila/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/dashboard': typeof DashboardRoute
  '/exercicios': typeof ExerciciosRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/responder': typeof ResponderRouteWithChildren
  '/signup': typeof SignupRoute
  '/suporte': typeof SuporteRoute
  '/apostila/$id': typeof ApostilaIdRoute
  '/responder/$apostilaId': typeof ResponderApostilaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/dashboard': typeof DashboardRoute
  '/exercicios': typeof ExerciciosRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/responder': typeof ResponderRouteWithChildren
  '/signup': typeof SignupRoute
  '/suporte': typeof SuporteRoute
  '/apostila/$id': typeof ApostilaIdRoute
  '/responder/$apostilaId': typeof ResponderApostilaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/dashboard': typeof DashboardRoute
  '/exercicios': typeof ExerciciosRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/responder': typeof ResponderRouteWithChildren
  '/signup': typeof SignupRoute
  '/suporte': typeof SuporteRoute
  '/apostila/$id': typeof ApostilaIdRoute
  '/responder/$apostilaId': typeof ResponderApostilaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/complete-profile'
    | '/dashboard'
    | '/exercicios'
    | '/login'
    | '/reset-password'
    | '/responder'
    | '/signup'
    | '/suporte'
    | '/apostila/$id'
    | '/responder/$apostilaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/complete-profile'
    | '/dashboard'
    | '/exercicios'
    | '/login'
    | '/reset-password'
    | '/responder'
    | '/signup'
    | '/suporte'
    | '/apostila/$id'
    | '/responder/$apostilaId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/complete-profile'
    | '/dashboard'
    | '/exercicios'
    | '/login'
    | '/reset-password'
    | '/responder'
    | '/signup'
    | '/suporte'
    | '/apostila/$id'
    | '/responder/$apostilaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CompleteProfileRoute: typeof CompleteProfileRoute
  DashboardRoute: typeof DashboardRoute
  ExerciciosRoute: typeof ExerciciosRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResponderRoute: typeof ResponderRouteWithChildren
  SignupRoute: typeof SignupRoute
  SuporteRoute: typeof SuporteRoute
  ApostilaIdRoute: typeof ApostilaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responder': {
      id: '/responder'
      path: '/responder'
      fullPath: '/responder'
      preLoaderRoute: typeof ResponderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercicios': {
      id: '/exercicios'
      path: '/exercicios'
      fullPath: '/exercicios'
      preLoaderRoute: typeof ExerciciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responder/$apostilaId': {
      id: '/responder/$apostilaId'
      path: '/$apostilaId'
      fullPath: '/responder/$apostilaId'
      preLoaderRoute: typeof ResponderApostilaIdRouteImport
      parentRoute: typeof ResponderRoute
    }
    '/apostila/$id': {
      id: '/apostila/$id'
      path: '/apostila/$id'
      fullPath: '/apostila/$id'
      preLoaderRoute: typeof ApostilaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ResponderRouteChildren {
  ResponderApostilaIdRoute: typeof ResponderApostilaIdRoute
}

const ResponderRouteChildren: ResponderRouteChildren = {
  ResponderApostilaIdRoute: ResponderApostilaIdRoute,
}

const ResponderRouteWithChildren = ResponderRoute._addFileChildren(
  ResponderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CompleteProfileRoute: CompleteProfileRoute,
  DashboardRoute: DashboardRoute,
  ExerciciosRoute: ExerciciosRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResponderRoute: ResponderRouteWithChildren,
  SignupRoute: SignupRoute,
  SuporteRoute: SuporteRoute,
  ApostilaIdRoute: ApostilaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
