/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResponderRouteImport } from './routes/responder'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExerciciosRouteImport } from './routes/exercicios'
import { Route as DocumentacaoRouteImport } from './routes/documentacao'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as AudiolivrosRouteImport } from './routes/audiolivros'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResponderApostilaIdRouteImport } from './routes/responder.$apostilaId'
import { Route as AudiolivrosGenesisRouteImport } from './routes/audiolivros.genesis'
import { Route as ApostilaIdRouteImport } from './routes/apostila.$id'
import { Route as AudiolivrosGenesisCapIdRouteImport } from './routes/audiolivros.genesis.$capId'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponderRoute = ResponderRouteImport.update({
  id: '/responder',
  path: '/responder',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciciosRoute = ExerciciosRouteImport.update({
  id: '/exercicios',
  path: '/exercicios',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentacaoRoute = DocumentacaoRouteImport.update({
  id: '/documentacao',
  path: '/documentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiolivrosRoute = AudiolivrosRouteImport.update({
  id: '/audiolivros',
  path: '/audiolivros',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponderApostilaIdRoute = ResponderApostilaIdRouteImport.update({
  id: '/$apostilaId',
  path: '/$apostilaId',
  getParentRoute: () => ResponderRoute,
} as any)
const AudiolivrosGenesisRoute = AudiolivrosGenesisRouteImport.update({
  id: '/genesis',
  path: '/genesis',
  getParentRoute: () => AudiolivrosRoute,
} as any)
const ApostilaIdRoute = ApostilaIdRouteImport.update({
  id: '/apostila/$id',
  path: '/apostila/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiolivrosGenesisCapIdRoute = AudiolivrosGenesisCapIdRouteImport.update({
  id: '/$capId',
  path: '/$capId',
  getParentRoute: () => AudiolivrosGenesisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audiolivros': typeof AudiolivrosRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/dashboard': typeof DashboardRoute
  '/documentacao': typeof DocumentacaoRoute
  '/exercicios': typeof ExerciciosRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/responder': typeof ResponderRouteWithChildren
  '/signup': typeof SignupRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/apostila/$id': typeof ApostilaIdRoute
  '/audiolivros/genesis': typeof AudiolivrosGenesisRouteWithChildren
  '/responder/$apostilaId': typeof ResponderApostilaIdRoute
  '/audiolivros/genesis/$capId': typeof AudiolivrosGenesisCapIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audiolivros': typeof AudiolivrosRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/dashboard': typeof DashboardRoute
  '/documentacao': typeof DocumentacaoRoute
  '/exercicios': typeof ExerciciosRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/responder': typeof ResponderRouteWithChildren
  '/signup': typeof SignupRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/apostila/$id': typeof ApostilaIdRoute
  '/audiolivros/genesis': typeof AudiolivrosGenesisRouteWithChildren
  '/responder/$apostilaId': typeof ResponderApostilaIdRoute
  '/audiolivros/genesis/$capId': typeof AudiolivrosGenesisCapIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audiolivros': typeof AudiolivrosRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/dashboard': typeof DashboardRoute
  '/documentacao': typeof DocumentacaoRoute
  '/exercicios': typeof ExerciciosRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/responder': typeof ResponderRouteWithChildren
  '/signup': typeof SignupRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/apostila/$id': typeof ApostilaIdRoute
  '/audiolivros/genesis': typeof AudiolivrosGenesisRouteWithChildren
  '/responder/$apostilaId': typeof ResponderApostilaIdRoute
  '/audiolivros/genesis/$capId': typeof AudiolivrosGenesisCapIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/audiolivros'
    | '/complete-profile'
    | '/dashboard'
    | '/documentacao'
    | '/exercicios'
    | '/login'
    | '/perfil'
    | '/privacidade'
    | '/reset-password'
    | '/responder'
    | '/signup'
    | '/suporte'
    | '/termos'
    | '/apostila/$id'
    | '/audiolivros/genesis'
    | '/responder/$apostilaId'
    | '/audiolivros/genesis/$capId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/audiolivros'
    | '/complete-profile'
    | '/dashboard'
    | '/documentacao'
    | '/exercicios'
    | '/login'
    | '/perfil'
    | '/privacidade'
    | '/reset-password'
    | '/responder'
    | '/signup'
    | '/suporte'
    | '/termos'
    | '/apostila/$id'
    | '/audiolivros/genesis'
    | '/responder/$apostilaId'
    | '/audiolivros/genesis/$capId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/audiolivros'
    | '/complete-profile'
    | '/dashboard'
    | '/documentacao'
    | '/exercicios'
    | '/login'
    | '/perfil'
    | '/privacidade'
    | '/reset-password'
    | '/responder'
    | '/signup'
    | '/suporte'
    | '/termos'
    | '/apostila/$id'
    | '/audiolivros/genesis'
    | '/responder/$apostilaId'
    | '/audiolivros/genesis/$capId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AudiolivrosRoute: typeof AudiolivrosRouteWithChildren
  CompleteProfileRoute: typeof CompleteProfileRoute
  DashboardRoute: typeof DashboardRoute
  DocumentacaoRoute: typeof DocumentacaoRoute
  ExerciciosRoute: typeof ExerciciosRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResponderRoute: typeof ResponderRouteWithChildren
  SignupRoute: typeof SignupRoute
  SuporteRoute: typeof SuporteRoute
  TermosRoute: typeof TermosRoute
  ApostilaIdRoute: typeof ApostilaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responder': {
      id: '/responder'
      path: '/responder'
      fullPath: '/responder'
      preLoaderRoute: typeof ResponderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercicios': {
      id: '/exercicios'
      path: '/exercicios'
      fullPath: '/exercicios'
      preLoaderRoute: typeof ExerciciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentacao': {
      id: '/documentacao'
      path: '/documentacao'
      fullPath: '/documentacao'
      preLoaderRoute: typeof DocumentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiolivros': {
      id: '/audiolivros'
      path: '/audiolivros'
      fullPath: '/audiolivros'
      preLoaderRoute: typeof AudiolivrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responder/$apostilaId': {
      id: '/responder/$apostilaId'
      path: '/$apostilaId'
      fullPath: '/responder/$apostilaId'
      preLoaderRoute: typeof ResponderApostilaIdRouteImport
      parentRoute: typeof ResponderRoute
    }
    '/audiolivros/genesis': {
      id: '/audiolivros/genesis'
      path: '/genesis'
      fullPath: '/audiolivros/genesis'
      preLoaderRoute: typeof AudiolivrosGenesisRouteImport
      parentRoute: typeof AudiolivrosRoute
    }
    '/apostila/$id': {
      id: '/apostila/$id'
      path: '/apostila/$id'
      fullPath: '/apostila/$id'
      preLoaderRoute: typeof ApostilaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiolivros/genesis/$capId': {
      id: '/audiolivros/genesis/$capId'
      path: '/$capId'
      fullPath: '/audiolivros/genesis/$capId'
      preLoaderRoute: typeof AudiolivrosGenesisCapIdRouteImport
      parentRoute: typeof AudiolivrosGenesisRoute
    }
  }
}

interface AudiolivrosGenesisRouteChildren {
  AudiolivrosGenesisCapIdRoute: typeof AudiolivrosGenesisCapIdRoute
}

const AudiolivrosGenesisRouteChildren: AudiolivrosGenesisRouteChildren = {
  AudiolivrosGenesisCapIdRoute: AudiolivrosGenesisCapIdRoute,
}

const AudiolivrosGenesisRouteWithChildren =
  AudiolivrosGenesisRoute._addFileChildren(AudiolivrosGenesisRouteChildren)

interface AudiolivrosRouteChildren {
  AudiolivrosGenesisRoute: typeof AudiolivrosGenesisRouteWithChildren
}

const AudiolivrosRouteChildren: AudiolivrosRouteChildren = {
  AudiolivrosGenesisRoute: AudiolivrosGenesisRouteWithChildren,
}

const AudiolivrosRouteWithChildren = AudiolivrosRoute._addFileChildren(
  AudiolivrosRouteChildren,
)

interface ResponderRouteChildren {
  ResponderApostilaIdRoute: typeof ResponderApostilaIdRoute
}

const ResponderRouteChildren: ResponderRouteChildren = {
  ResponderApostilaIdRoute: ResponderApostilaIdRoute,
}

const ResponderRouteWithChildren = ResponderRoute._addFileChildren(
  ResponderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AudiolivrosRoute: AudiolivrosRouteWithChildren,
  CompleteProfileRoute: CompleteProfileRoute,
  DashboardRoute: DashboardRoute,
  DocumentacaoRoute: DocumentacaoRoute,
  ExerciciosRoute: ExerciciosRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResponderRoute: ResponderRouteWithChildren,
  SignupRoute: SignupRoute,
  SuporteRoute: SuporteRoute,
  TermosRoute: TermosRoute,
  ApostilaIdRoute: ApostilaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
